on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install Dasel
        run: curl -sSLf "$(curl -sSLf https://api.github.com/repos/tomwright/dasel/releases/latest | grep browser_download_url | grep linux_amd64 | grep -v .gz | cut -d\" -f 4)" -L -o dasel && chmod +x dasel
      - name: Run dasel
        run: |
          ./dasel put -t string -f example.yaml -s 'some.path' -v myvalue -o example.yaml \ 
          ./dasel -f example.yaml -s 'some.path' \ 
          ./dasel -f example.yaml
